-- Add all missing NotificationType enum values
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_UPDATE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REMINDER_NO_PHOTO';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REMINDER_INACTIVE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REMINDER_VIDEOCALL_CONFIG';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VIDEOCALL_BOOKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SERVICE_REQUEST_NEW';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'UMATE_NEW_SUBSCRIBER';
