ALTER TABLE "Banner"
ADD COLUMN "imageFocusX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "imageFocusY" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN "imageZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
