-- Ensure REMINDER_INACTIVE exists in NotificationType enum
-- The value was added in 20260329100000_bugfix_indexes_and_enum but may not have been applied
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REMINDER_INACTIVE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REMINDER_NO_PHOTO';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REMINDER_VIDEOCALL_CONFIG';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VIDEOCALL_BOOKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SERVICE_REQUEST_NEW';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_UPDATE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'UMATE_NEW_SUBSCRIBER';
