-- AlterTable
ALTER TABLE "MotelRoom" ADD COLUMN IF NOT EXISTS "roomType" TEXT;
ALTER TABLE "MotelRoom" ADD COLUMN IF NOT EXISTS "amenities" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "MotelRoom" ADD COLUMN IF NOT EXISTS "photoUrls" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "MotelRoom" ADD COLUMN IF NOT EXISTS "price3h" INTEGER;
ALTER TABLE "MotelRoom" ADD COLUMN IF NOT EXISTS "price6h" INTEGER;
ALTER TABLE "MotelRoom" ADD COLUMN IF NOT EXISTS "priceNight" INTEGER;
ALTER TABLE "MotelRoom" ADD COLUMN IF NOT EXISTS "location" TEXT;

-- AlterTable
ALTER TABLE "MotelPromotion" ADD COLUMN IF NOT EXISTS "discountClp" INTEGER;
ALTER TABLE "MotelPromotion" ADD COLUMN IF NOT EXISTS "roomId" UUID;
ALTER TABLE "MotelPromotion" ADD COLUMN IF NOT EXISTS "roomIds" UUID[] DEFAULT ARRAY[]::UUID[];
